services:
  database:
    build: ./modules/backend
    container_name: database
    environment:
      - DB_HOST=mysql_master
      - DB_READ_HOST=mysql_slave
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=hotel_db
      - ZBX_HOSTNAME=Hotel-Backend-DB
      - ZBX_SERVER_HOST=192.168.1.100  # Change to your Zabbix Server IP
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mysql_master
      - mysql_slave

  mysql_master:
    build: ./modules/mysql-master
    container_name: mysql_master
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hotel_db
      - ZBX_HOSTNAME=Hotel-SQL-Master
      - ZBX_SERVER_HOST=192.168.1.100  # Change to your Zabbix Server IP
    ports:
      - "3306:3306"
    volumes:
      - mysql_master_data:/var/lib/mysql
    restart: always

  mysql_slave:
    build: ./modules/mysql-slave
    container_name: mysql_slave
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - ZBX_HOSTNAME=Hotel-SQL-Slave
      - ZBX_SERVER_HOST=192.168.1.100  # Change to your Zabbix Server IP
    ports:
      - "3307:3306"
    volumes:
      - mysql_slave_data:/var/lib/mysql
    restart: always
    depends_on:
      - mysql_master

  web:
    build: ./modules/frontend
    container_name: web
    environment:
      - ZBX_HOSTNAME=Hotel-Frontend-Web
      - ZBX_SERVER_HOST=192.168.1.100  # Change to your Zabbix Server IP
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - database

volumes:
  mysql_master_data:
  mysql_slave_data:
